services:
  maputnik:
    image: ghcr.io/maplibre/maputnik:main
    platform: linux/amd64
    ports:
      - "3000:8000"
  file-server:
    image: halverneus/static-file-server
    ports:
      - "3001:8080"
    volumes:
      - ./pmtiles:/web
    environment:
      - CORS=true
